Fix FSAL undefined reference to mtr_ functions
This error happens when ganesha is compiled with
-DCMAKE_BUILD_TYPE=Release, because gcc link time optimization is
enabled, causing code of mtr_ functions to be removed from ganesha
executable.